# Markdown配置
markdown:
  preset: 'default'
  render:
    html: true
    xhtmlOut: false
    langPrefix: 'language-'
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  enable_rules:
  disable_rules:
  plugins:
    - markdown-it-container
  anchors:
    level: 2
    collisionSuffix: ''
    permalink: false
    permalinkClass: 'header-anchor'
    permalinkSide: 'left'
    permalinkSymbol: '¶'
    case: 0
    separator: '-'
  images:
    lazyload: false
    prepend_root: false
    post_asset: false
  inline: false

# 站点地图
sitemap:
  path: sitemap.xml
  
# 插件
plugins:
  - hexo-renderer-markdown-it 

# Social links configuration
social:
  - name: github
    url: 'https://github.com/zsf2025'
    icon: 'fa-github'
  - name: envelope
    url: 'mailto:18072150332@fudan.edu.cn'
    icon: 'fa-envelope'
  - name: weixin
    url: '#'
    icon: 'fa-weixin'
    qrcode: '/images/wechat-qrcode.png'

# 菜单
menus:
  - name: 首页
    url: '/'
  - name: 最新文章
    url: '#articles'
  - name: 精品案例
    url: '#demo'
  - name: 关于
    url: '#about'

# Demo
demo:
  enable: true
  items:
    - title: markdown文章转微信公众号文章工具
      description: 简单易用的markdown文章转微信公众号文章工具，支持代码高亮，一键转换
      url: /html/markdownToWX.html
    - title: 专业级GIS映射工具
      description: 上传背景，输入四个点经纬度，矫正后方可得到准确的地区经纬图，可以在上面新增精准的点位，一个工业场景工具 
      url: /html/GIS.html
    - title: CAD平面标记点位工具
      description: cad动态点位路径绘制工具
      url: /html/cad.html